name: Feature request
description: Propose an enhancement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior you want.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives or trade-offs?
  - type: dropdown
    id: breaking
    attributes:
      label: Breaking change?
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
